-- AlterTable
ALTER TABLE "Task" ADD COLUMN "endDate" DATETIME;
ALTER TABLE "Task" ADD COLUMN "loe" INTEGER;
ALTER TABLE "Task" ADD COLUMN "sequence" REAL;
ALTER TABLE "Task" ADD COLUMN "startDate" DATETIME;
